#Resources/services.yml
parameters:
    assogest_user_provider.class: Assogest\Bundle\UserBundle\Provider\FOSUBUserProvider
 
services:
    assogest_user_provider:
        class: "%assogest_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{google: google_id}]